name: rock_classifier
description: "A new Flutter project."
publish_to: "none"

# Lấy phiên bản mới hơn từ stonelens
version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Cloud Services
  firebase_core: ^3.13.0 # Cập nhật từ stonelens
  cloud_firestore: ^5.6.7 # Cập nhật từ stonelens
  firebase_auth: ^5.5.3 # Cập nhật từ stonelens
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5 # Cập nhật từ stonelens

  # State Management
  provider: ^6.1.5 # Cập nhật từ stonelens

  # Authentication
  google_sign_in: ^6.3.0 # Thêm từ stonelens
  flutter_facebook_auth: ^7.1.2 # Thêm từ stonelens
  sign_in_with_apple: ^7.0.1 # Thêm từ stonelens

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2808.1
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  lottie: ^2.7.0 # Thêm từ stonelens

  # Utilities & Helpers
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5 # Chuyển từ dev_dependencies và thêm phiên bản
  go_router: ^15.0.0
  excel: ^4.0.6
  file_picker: ^10.1.6
  path: ^1.9.0
  easy_localization: ^3.0.7+1
  url_launcher: ^6.3.1
  camera: ^0.10.5+9 # Thêm từ stonelens

  # Machine Learning & Image Processing
  tflite_flutter: ^0.11.0
  image: ^4.3.0 # Cập nhật phiên bản mới hơn
  google_generative_ai: ^0.4.7
  share_plus: ^11.0.0
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # Thêm từ stonelens

# Cấu hình icon cho ứng dụng (thêm từ stonelens)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icontest.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Hợp nhất và loại bỏ trùng lặp từ cả hai file
  assets:
    - assets/
    - assets/translations/
    - assets/model/test3.tflite
    - .env
